#!/usr/bin/env bash
# mint-jwt.sh — sign a JWT with the demo IdP key (demo-scripts/.jwt/private.pem).
# Plain openssl, nothing hidden: RS256 over base64url(header).base64url(claims).
#
#   echo '{"iss":"https://idp.demo.example/","sub":"alice@corp.example",...}' \
#     | ./demo-scripts/scripts/mint-jwt.sh -
#
# The keypair is generated by ./demo-scripts/llm-gateway.sh; the matching public
# JWKS (demo-scripts/.jwt/jwks.json) is what the gateway's JWT policy trusts.
set -Eeuo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KEY="$SCRIPT_DIR/../.jwt/private.pem"
[ -f "$KEY" ] || { echo "no $KEY — run ./demo-scripts/llm-gateway.sh first" >&2; exit 1; }

CLAIMS="${1:?pass the claims JSON (or - for stdin)}"
[ "$CLAIMS" = "-" ] && CLAIMS=$(cat)

b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }

HEADER=$(printf '{"alg":"RS256","typ":"JWT","kid":"demo-idp"}' | b64url)
PAYLOAD=$(printf '%s' "$CLAIMS" | b64url)
SIG=$(printf '%s.%s' "$HEADER" "$PAYLOAD" | openssl dgst -sha256 -sign "$KEY" -binary | b64url)
printf '%s.%s.%s\n' "$HEADER" "$PAYLOAD" "$SIG"
