apiVersion: v1
kind: Secret
metadata:
  name: auth0-token-exchange
  namespace: agentgateway-system
type: Opaque
stringData:
  type: oauth
  app_id: auth0
  client_id: "<auth0-m2m-client-id>"
  client_secret: "<auth0-m2m-client-secret>"
  authorize_url: "https://acme.eu.auth0.com/authorize"
  access_token_url: "https://acme.eu.auth0.com/oauth/token"
  scopes: "openid mcp:invoke offline_access"
  redirect_uri: "https://agentgateway.acme.io/age/elicitations"
