# AUTOGENERATED FILE: DO NOT EDIT
# Generated by the AgentRegistry CLI.

import json
import os
import re
from typing import List, Optional, Union

from google.adk.tools.base_toolset import ToolPredicate
from google.adk.tools.mcp_tool.mcp_toolset import MCPToolset, StreamableHTTPConnectionParams


_MCP_SERVERS = [
]


def _resolve_env_vars(value: str) -> str:
    """Resolve ${VAR} placeholders using the local environment."""

    def replace_var(match):
        var_name = match.group(1)
        return os.environ.get(var_name, match.group(0))

    return re.sub(r"\$\{([^}]+)\}", replace_var, value)


def _get_terminate_on_close() -> bool:
    """Get the terminate_on_close setting from environment variable.

    Defaults to True for backward compatibility.
    Set MCP_TERMINATE_ON_CLOSE=false for stateless MCP servers.
    """
    return os.environ.get("MCP_TERMINATE_ON_CLOSE", "true").lower() != "false"


def _get_connect_timeout() -> float:
    """Connect/request timeout (seconds) for MCP streamable-http toolsets.

    Defaults to 60s. The google-adk default is 5s, which is too short for
    remote MCP servers reached through authenticated gateways or cold-start
    compute — first-connection latency on those paths regularly exceeds 5s.
    Override via MCP_CONNECT_TIMEOUT env var (float seconds).
    """
    try:
        return float(os.environ.get("MCP_CONNECT_TIMEOUT", "60"))
    except ValueError:
        return 60.0


def _load_runtime_mcp_servers() -> List[dict]:
    """Load MCP servers from MCP_SERVERS_CONFIG env var (JSON).

    This env var is injected at deploy time by the registry backend
    after resolving all MCP server refs from the DB.
    """
    env_config = os.environ.get("MCP_SERVERS_CONFIG")
    if not env_config:
        return []
    try:
        data = json.loads(env_config)
        if isinstance(data, list):
            return data
    except json.JSONDecodeError:
        pass
    return []


def _get_all_mcp_servers() -> List[dict]:
    """Get all MCP servers, merging baked-in and runtime-resolved servers."""
    # TODO(legacy): remove _MCP_SERVERS merge once declarative API is the only supported path
    servers = list(_MCP_SERVERS)  # Only command/remote servers (registry filtered out at template time)

    # Load runtime-resolved servers (from MCP_SERVERS_CONFIG env var)
    runtime_servers = _load_runtime_mcp_servers()

    # Append runtime servers, avoiding duplicates by name
    existing_names = {s.get("name") for s in servers}
    for runtime_server in runtime_servers:
        server_name = runtime_server.get("name")
        if server_name and server_name not in existing_names:
            servers.append(runtime_server)
            existing_names.add(server_name)

    return servers


def _tool_name_prefix(server_name: str) -> str:
    """Sanitize the server name into a tool-name-safe prefix.

    The LLM API rejects requests where two tools share a name, but multiple
    MCP servers commonly expose the same tool (e.g. `echo` on every demo
    server). Prefixing each toolset's tools with the server name makes them
    globally unique. ADK's tool name grammar is alphanumeric + underscore,
    so any non-conforming chars in the server name (hyphens, dots) collapse
    to underscores.

    Caveat: distinct server names that differ only by punctuation collapse
    to the same prefix (e.g. `my-foo`, `my.foo`, `my_foo` all → `my_foo`).
    Server names are expected to be distinct identifiers, not differ only by
    punctuation; if you hit this, rename one of the servers.
    """
    return re.sub(r"[^a-zA-Z0-9_]", "_", server_name)


def get_mcp_tools(
    server_names: Optional[List[str]] = None,
    server_filters: Optional[Union[ToolPredicate, List[str]]] = None,
    global_filter: Optional[Union[ToolPredicate, List[str]]] = None,
) -> List[MCPToolset]:
    """Return MCP toolsets for the configured servers.

    Each toolset's tools are prefixed with the sanitized server name so
    multiple MCPs can share underlying tool names without colliding when
    the merged list reaches the LLM API.

    Environment variables:
        MCP_TERMINATE_ON_CLOSE: Set to "false" for stateless MCP servers.
            Defaults to "true" for backward compatibility.
        MCP_CONNECT_TIMEOUT: Float seconds for MCP connect/request timeout.
            Defaults to 60s (raised from google-adk's 5s) so remote MCPs
            reached through gateways or cold-start compute have time to
            respond on first connection.
    """

    servers = _get_all_mcp_servers()

    if server_names is not None:
        servers = [s for s in servers if s.get("name") in server_names]

    terminate_on_close = _get_terminate_on_close()
    connect_timeout = _get_connect_timeout()

    toolsets = []
    for server in servers:
        server_name = server["name"]
        url = f"http://{server_name}:3000/mcp" if server["type"] == "command" else server["url"]
        url = _resolve_env_vars(url)

        headers = {}
        if "headers" in server and server["headers"]:
            for key, value in server["headers"].items():
                headers[key] = _resolve_env_vars(value)

        predicate = None
        if server_filters and server_name in server_filters:
            predicate = server_filters[server_name]
        elif global_filter is not None:
            predicate = global_filter

        if headers:
            connection_params = StreamableHTTPConnectionParams(
                url=url, headers=headers, timeout=connect_timeout, terminate_on_close=terminate_on_close
            )
        else:
            connection_params = StreamableHTTPConnectionParams(
                url=url, timeout=connect_timeout, terminate_on_close=terminate_on_close
            )

        toolset_kwargs = {
            "connection_params": connection_params,
            "tool_name_prefix": _tool_name_prefix(server_name),
        }
        if predicate is not None:
            toolset_kwargs["tool_filter"] = predicate
        toolset = MCPToolset(**toolset_kwargs)

        toolsets.append(toolset)

    return toolsets

