#!/usr/bin/env bash
# Provision the AWS side (both portfolio accounts) and write deploy/.env.tofu
# for the later scripts. Requires tofu and live AWS sessions for both profiles
# named in tofu/terraform.tfvars.
set -euo pipefail
LAB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$LAB_DIR/tofu"

[ -f terraform.tfvars ] || { echo "copy terraform.tfvars.example to terraform.tfvars and fill in your profiles"; exit 1; }

tofu init -input=false
tofu apply -input=false -auto-approve

mkdir -p "$LAB_DIR/deploy"
ENV_FILE="$LAB_DIR/deploy/.env.tofu"

json() { tofu output -json "$1"; }
raw()  { tofu output -raw  "$1"; }

{
  echo "# Generated by scripts/10-tofu.sh - never commit."
  echo "PORTFOLIO_A_ACCOUNT_ID=$(json portfolio_a | jq -r .account_id)"
  echo "PORTFOLIO_A_REGION=$(json portfolio_a | jq -r .region)"
  echo "PORTFOLIO_A_AR_ROLE_ARN=$(json portfolio_a | jq -r .agentregistry_role)"
  echo "PORTFOLIO_A_INVOKE_ROLE_ARN=$(json portfolio_a | jq -r .invoke_role)"
  echo "PORTFOLIO_A_EXTERNAL_ID=$(raw portfolio_a_external_id)"
  echo "PORTFOLIO_B_ACCOUNT_ID=$(json portfolio_b | jq -r .account_id)"
  echo "PORTFOLIO_B_REGION=$(json portfolio_b | jq -r .region)"
  echo "PORTFOLIO_B_AR_ROLE_ARN=$(json portfolio_b | jq -r .agentregistry_role)"
  echo "PORTFOLIO_B_INVOKE_ROLE_ARN=$(json portfolio_b | jq -r .invoke_role)"
  echo "PORTFOLIO_B_EXTERNAL_ID=$(raw portfolio_b_external_id)"
  echo "AGW_AWS_ACCESS_KEY_ID=$(raw agw_ambient_access_key_id)"
  echo "AGW_AWS_SECRET_ACCESS_KEY=$(raw agw_ambient_secret_access_key)"
  echo "AR_AWS_ACCESS_KEY_ID=$(raw ar_control_access_key_id)"
  echo "AR_AWS_SECRET_ACCESS_KEY=$(raw ar_control_secret_access_key)"
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo "Wrote $ENV_FILE"
