#!/usr/bin/env bash
# 02-agentgateway.sh — Solo Enterprise for agentgateway + the ingress Gateway
# that fronts Keycloak, AgentRegistry and the MCP server.
#
# Pinned to v2026.7.1 (current Stable/LTS). 2026.7.0 is the floor: it added
# extended label selectors and default labelset support, which is what lets the
# verdict label pull in the HITL policy without per-agent YAML.
#
# Writes .env.verdict with the LB IP and the sslip hostnames every later script
# reads via lib.sh.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAB_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

require_secrets
gar_login

step "Installing agentgateway CRDs $AGW_VERSION"
helm --kube-context "$CTX" upgrade --install enterprise-agentgateway-crds \
  "$AGW_CHARTS/enterprise-agentgateway-crds" \
  -n "$AGW_NS" --create-namespace --version "$AGW_VERSION" \
  --wait --timeout 5m >/dev/null
ok "CRDs installed"

step "Installing agentgateway control plane $AGW_VERSION"
log "Enterprise images pull from GAR — progress every 15s below"
# The chart's licence path is licensing.licenseKey (confirmed with
# `helm show values` on v2026.7.1). It is NOT license.value — that shape belongs
# to other Solo charts and silently leaves the gateway unlicensed here.
helm_install_with_progress enterprise-agentgateway \
  "$AGW_CHARTS/enterprise-agentgateway" "$AGW_NS" \
  --version "$AGW_VERSION" \
  --set licensing.licenseKey="$AGW_LICENSE_KEY" \
  --wait --timeout 10m
ok "control plane installed"

step "Verifying the GatewayClass"
if kc get gatewayclass enterprise-agentgateway >/dev/null 2>&1; then
  ok "GatewayClass enterprise-agentgateway registered"
else
  die "GatewayClass enterprise-agentgateway missing — check the licence and the chart version"
fi

# ── ingress Gateway + LB IP ───────────────────────────────────────────────────
# One HTTP Gateway on a MetalLB LoadBalancer IP. Everything the host needs to
# reach (Keycloak, the registry API, the MCP endpoints) hangs off it as an
# HTTPRoute, addressed by a *.<LB-IP>.sslip.io hostname.
step "Ingress Gateway (LoadBalancer) + sslip.io hostnames"
kc apply -f "$LAB_ROOT/yaml/agentgateway/00-ingress-gateway.yaml" >/dev/null
kc -n "$AGW_NS" wait --for=condition=Programmed gateway/verdict-ingress --timeout=180s >/dev/null
LB=""
for _ in $(seq 1 40); do
  LB="$(kc -n "$AGW_NS" get gateway verdict-ingress \
        -o jsonpath='{.status.addresses[0].value}' 2>/dev/null)"
  [[ -n "$LB" ]] && break
  sleep 3
done
[[ -n "$LB" ]] || die "verdict-ingress got no LoadBalancer IP — is MetalLB healthy?"

cat > "$LAB_ROOT/.env.verdict" <<EOF
# GENERATED by scripts/02-agentgateway.sh — the platform facts every later
# script reads. Safe to delete; re-created on the next run.
LB=${LB}
KEYCLOAK_HOST=keycloak.${LB}.sslip.io
AR_HOST=agentregistry.${LB}.sslip.io
MCP_HOST=mcp.${LB}.sslip.io
KEYCLOAK_ISSUER=http://keycloak.${LB}.sslip.io/realms/${KEYCLOAK_REALM}
ARCTL_API_BASE_URL=http://agentregistry.${LB}.sslip.io
EOF
ok "LB ${LB}"
log "keycloak      → keycloak.${LB}.sslip.io"
log "agentregistry → agentregistry.${LB}.sslip.io"
log "mcp           → mcp.${LB}.sslip.io"
ok "wrote $LAB_ROOT/.env.verdict"

step "agentgateway ready"
echo "  Next: ./scripts/03-keycloak.sh" >&2
