#!/usr/bin/env bash
# 03-keycloak.sh — Keycloak with the `agentregistry` realm, plus the ingress
# routes for Keycloak and the AgentRegistry API.
#
# One realm serves both AgentRegistry and kagent, so a single identity
# (admin-user, group `admins`) is the developer publishing agents and the
# operator reading the catalogue. The lab is about the verdict, not about RBAC —
# agentregistry-governance-kind is the lab that splits identities.
#
# Scrapes the two confidential client secrets out of Keycloak after import,
# because the realm JSON ships placeholder secrets and the charts need the real
# ones.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAB_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

[[ -n "${LB:-}" ]] || die "LB not set — run ./scripts/02-agentgateway.sh first"

step "Keycloak (realm ${KEYCLOAK_REALM}) in ${KEYCLOAK_NS}"
log "KC_HOSTNAME = ${KEYCLOAK_HOST}"
kc -n "$KEYCLOAK_NS" create configmap keycloak-realm-import \
  --from-file=agentregistry-realm.json="$LAB_ROOT/yaml/keycloak/agentregistry-realm.json" \
  --dry-run=client -o yaml | kc apply -f - >/dev/null
sed "s/__KEYCLOAK_HOST__/${KEYCLOAK_HOST}/" "$LAB_ROOT/yaml/keycloak/keycloak.yaml" \
  | kc apply -f - >/dev/null
log "waiting for Keycloak (image pull + realm import takes 1-2 min)…"
kc -n "$KEYCLOAK_NS" rollout status statefulset/keycloak --timeout=300s >/dev/null \
  || die "keycloak did not become Ready"
ok "Keycloak up"

step "Ingress routes for Keycloak + AgentRegistry"
sed "s/__LB__/${LB}/g" "$LAB_ROOT/yaml/agentgateway/01-platform-routes.yaml" \
  | kc apply -f - >/dev/null
ok "HTTPRoutes applied (the agentregistry route resolves once phase 04 installs it)"

# ── scrape the confidential client secrets ────────────────────────────────────
# The realm import cannot carry usable secrets for confidential clients, so read
# them back through the admin API over a short-lived port-forward.
step "Scraping confidential client secrets (ar-backend, kagent-backend)"
scrape() {
  local client="$1" pf admtok cid
  kc -n "$KEYCLOAK_NS" port-forward svc/keycloak 18099:8080 >/dev/null 2>&1 &
  pf=$!
  for _ in $(seq 1 30); do
    curl -sf -m2 http://localhost:18099/realms/master/.well-known/openid-configuration >/dev/null 2>&1 && break
    sleep 1
  done
  admtok="$(curl -s -X POST http://localhost:18099/realms/master/protocol/openid-connect/token \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    -d 'grant_type=password&client_id=admin-cli&username=admin&password=admin' \
    | jq -r '.access_token // empty')"
  cid="$(curl -s -H "Authorization: Bearer $admtok" \
    "http://localhost:18099/admin/realms/${KEYCLOAK_REALM}/clients?clientId=${client}" \
    | jq -r '.[0].id // empty')"
  curl -s -H "Authorization: Bearer $admtok" \
    "http://localhost:18099/admin/realms/${KEYCLOAK_REALM}/clients/${cid}/client-secret" \
    | jq -r '.value // empty'
  kill "$pf" 2>/dev/null || true
}
AR_BACKEND_SECRET="$(scrape "$AR_BACKEND_CLIENT")"
KAGENT_BACKEND_SECRET="$(scrape "$KAGENT_BACKEND_CLIENT")"
[[ -n "$AR_BACKEND_SECRET" && -n "$KAGENT_BACKEND_SECRET" ]] \
  || die "could not scrape client secrets from Keycloak"

# Stash them for phase 04. Gitignored — they are regenerated on every install.
cat > "$LAB_ROOT/.env.oidc" <<EOF
# GENERATED by scripts/03-keycloak.sh. Realm client secrets, read back from
# Keycloak after import. Gitignored; re-created on every run.
AR_BACKEND_SECRET=${AR_BACKEND_SECRET}
KAGENT_BACKEND_SECRET=${KAGENT_BACKEND_SECRET}
EOF
ok "client secrets scraped → .env.oidc"

step "Verifying the issuer is reachable from the host"
for _ in $(seq 1 40); do
  curl -sf -m2 -o /dev/null "${KEYCLOAK_ISSUER}/.well-known/openid-configuration" && break
  sleep 3
done
if curl -sf -m5 -o /dev/null "${KEYCLOAK_ISSUER}/.well-known/openid-configuration"; then
  ok "issuer live: ${KEYCLOAK_ISSUER}"
else
  warn "issuer not reachable yet at ${KEYCLOAK_ISSUER} — phase 04 retries"
fi

step "Keycloak ready"
echo "  Next: ./scripts/04-kagent-registry.sh" >&2
